<h1>opendata.swiss API Notebook</h1>

<p>This notebook is dedicated to call the opendata.swiss API and extract data for our ADS Project. The data will enrich our rental price prediction models with relevant statistical data from Canton of Zurich. Most notably we are interested in the tax rates ("Steuerfuss") per municipality.<p>

In [9]:
import requests
import pandas as pd
import io

# CKAN API endpoint URL
api_url = "https://ckan.opendata.swiss/api/3/action/resource_show"

# Resource ID for the desired resource
resource_id = "c792c06b-9d43-4f63-bac3-f2e89006194d"  # Example resource ID

# Parameters for the API request
params = {
    "id": resource_id
}

# Send a GET request to retrieve resource information
response = requests.get(api_url, params=params)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the JSON response
    resource_info = response.json()

    # Get the URL of the resource
    resource_url = resource_info['result']['url']

    # Download the data from the resource URL
    data_response = requests.get(resource_url)

    # Load the data into a pandas DataFrame
    dataset_df = pd.read_csv(io.BytesIO(data_response.content))

   
else:
    print("Failed to retrieve resource information. Status code:", response.status_code)

In [11]:
dataset_df

,LAST_REFRESH,YEAR,COMMUNITY,BFSNR,FLAG,STF_O_KIRCHE1,STF_O_KIRCHE2,STF_O_KIRCHE3,DIFF_O_KIRCHE,STF_REF1,...,DIFF_REF,STF_KATH1,STF_KATH2,STF_KATH3,DIFF_KATH,STF_CKRKATH1,STF_CKRKATH2,STF_CKRKATH3,DIFF_CHRKATH,JUR_PERS
0,14.03.2024,2024,Aeugst a.A.,1,definitiv,92,NaN,NaN,-3,104,...,-3,105,NaN,NaN,-3,106,NaN,NaN,-3,104.35
1,14.03.2024,2024,Affoltern a.A.,2,definitiv,124,NaN,NaN,0,136,...,0,137,NaN,NaN,0,138,NaN,NaN,0,136.50
2,14.03.2024,2024,Bonstetten,3,definitiv,110,NaN,NaN,1,122,...,1,121,NaN,NaN,1,124,NaN,NaN,1,121.56
3,14.03.2024,2024,Hausen a.A.,4,definitiv,112,NaN,NaN,0,124,...,0,126,NaN,NaN,0,126,NaN,NaN,0,124.90
4,14.03.2024,2024,Hedingen,5,definitiv,100,NaN,NaN,0,112,...,0,113,NaN,NaN,0,114,NaN,NaN,0,112.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,14.03.2024,2024,Elgg,294,definitiv,119,NaN,NaN,4,133,...,4,133,NaN,NaN,4,133,NaN,NaN,4,133.00
156,14.03.2024,2024,Horgen,295,definitiv,90,NaN,NaN,0,100,...,0,97,NaN,NaN,0,104,NaN,NaN,0,98.50
157,14.03.2024,2024,Illnau-Effretikon,296,definitiv,110,NaN,NaN,0,123,...,0,123,122.0,NaN,0,124,NaN,NaN,0,123.00
158,14.03.2024,2024,Bauma,297,definitiv,120,NaN,NaN,0,134,...,0,133,NaN,NaN,0,134,NaN,NaN,0,133.70
159,14.03.2024,2024,Wiesendangen,298,definitiv,88,NaN,NaN,0,102,...,0,101,101.0,NaN,0,102,NaN,NaN,0,101.68

In [12]:
#safe data to csv
dataset_df.to_csv('steuerfuss.csv', index=False)