In [56]:
import pandas as pd

# filepath_einkommen = 'estv_income_rates_einkommen.csv'
# filepath_vermoegen = 'estv_income_rates_vermoegen.csv'
filepath_steuern = 'estv_income_rates.csv'
filepath_gemeinden = 'gemeindeverzeichnis_schweiz.csv'
filepath_locationfile ='../TablesDB/Location_v3_enriched.csv'

# columns_einkommen = ['Kantons-Id','Kanton','BfS-Id','Gemeinde','Kantonssteuer','Gemeindesteuer']
# columns_vermoegen = ['Kantons-Id','Kanton','BfS-Id','Gemeinde','Kantonssteuer','Gemeindesteuer']
columns_steuern = ['Kantons-Id','Kanton','BfS-Id','Gemeinde','Einkommenssteuer_Kanton','Einkommenssteuer_Gemeinde','Vermögenssteuer_Kanton','Vermögenssteuer_Gemeinde']
columns_gemeinden = ['Ortschaftsname','PLZ','Gemeindename','BFS-Nr','Kantonskürzel']

# df_einkommen_st = pd.read_csv(filepath_einkommen)[columns_einkommen]
# df_vermoegen_st = pd.read_csv(filepath_vermoegen)[columns_vermoegen]
df_steuern = pd.read_csv(filepath_steuern)[columns_steuern]
df_gemeinden = pd.read_csv(filepath_gemeinden, sep=";")[columns_gemeinden]
df_locationfile = pd.read_csv(filepath_locationfile)

df_gemeinden.rename(columns={'BFS-Nr':'BfS-Id', 'PLZ':'ZIP'}, inplace=True)

df_steuern

,Kantons-Id,Kanton,BfS-Id,Gemeinde,Einkommenssteuer_Kanton,Einkommenssteuer_Gemeinde,Vermögenssteuer_Kanton,Vermögenssteuer_Gemeinde
0,1,ZH,131,Adliswil,99.0,102.0,99.0,102.0
1,1,ZH,241,Aesch (ZH),99.0,91.0,99.0,91.0
2,1,ZH,1,Aeugst am Albis,99.0,95.0,99.0,95.0
3,1,ZH,2,Affoltern am Albis,99.0,124.0,99.0,124.0
4,1,ZH,211,Altikon,99.0,114.0,99.0,114.0
...,...,...,...,...,...,...,...,...
2131,26,JU,6722,Saulcy,285.0,220.0,285.0,220.0
2132,26,JU,6759,Soubey,285.0,225.0,285.0,225.0
2133,26,JU,6724,Soyhières,285.0,215.0,285.0,215.0
2134,26,JU,6730,Val Terbi,285.0,225.0,285.0,225.0
2135,26,JU,6806,Vendlincourt,285.0,230.0,285.0,230.0

In [57]:
df_steuern.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2136 entries, 0 to 2135
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Kantons-Id                 2136 non-null   int64
 1   Kanton                     2136 non-null   object
 2   BfS-Id                     2136 non-null   int64
 3   Gemeinde                   2136 non-null   object
 4   Einkommenssteuer_Kanton    2136 non-null   float64
 5   Einkommenssteuer_Gemeinde  2136 non-null   float64
 6   Vermögenssteuer_Kanton     2136 non-null   float64
 7   Vermögenssteuer_Gemeinde   2136 non-null   float64
dtypes: float64(4), int64(2), object(2)
memory usage: 133.6+ KB

<h3>Checking that columns to be merged have the same datatype<h3/>

In [58]:
df_gemeinden.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5737 entries, 0 to 5736
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Ortschaftsname  5737 non-null   object
 1   ZIP             5737 non-null   int64
 2   Gemeindename    5737 non-null   object
 3   BfS-Id          5737 non-null   int64
 4   Kantonskürzel   5717 non-null   object
dtypes: int64(2), object(3)
memory usage: 224.2+ KB

In [59]:
df_locationfile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11352 entries, 0 to 11351
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LocationId        11352 non-null  object
 1   Street            10644 non-null  object
 2   ZIP               11295 non-null  float64
 3   longitude         11352 non-null  float64
 4   latitude          11352 non-null  float64
 5   #supermarkets     11352 non-null  int64
 6   #foodandbeverage  11352 non-null  int64
dtypes: float64(3), int64(2), object(2)
memory usage: 620.9+ KB

<h3>Converting the ZIP values in the Location File from float to int<h3/>

In [60]:
df_locationfile['ZIP'] = pd.to_numeric(df_locationfile['ZIP'], errors='coerce').astype('Int64')

df_locationfile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11352 entries, 0 to 11351
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LocationId        11352 non-null  object
 1   Street            10644 non-null  object
 2   ZIP               11295 non-null  Int64
 3   longitude         11352 non-null  float64
 4   latitude          11352 non-null  float64
 5   #supermarkets     11352 non-null  int64
 6   #foodandbeverage  11352 non-null  int64
dtypes: Int64(1), float64(2), int64(2), object(2)
memory usage: 632.0+ KB

<h3>Merging the dataframes<h3/>

In [61]:
df_merged = pd.merge(df_locationfile, df_gemeinden, on='ZIP',how='left')
df_merged = pd.merge(df_merged, df_steuern, on='BfS-Id',how='left')
df_merged.head()

,LocationId,Street,ZIP,longitude,latitude,#supermarkets,#foodandbeverage,Ortschaftsname,Gemeindename,BfS-Id,Kantonskürzel,Kantons-Id,Kanton,Gemeinde,Einkommenssteuer_Kanton,Einkommenssteuer_Gemeinde,Vermögenssteuer_Kanton,Vermögenssteuer_Gemeinde
0,78753131-6d78-4d1e-a0e5-fc8b5f430570,NaN,6598,8.849665,46.175962,2,3,Tenero,Minusio,5118.0,TI,21.0,TI,Minusio,97.0,78.0,97.0,78.0
1,78753131-6d78-4d1e-a0e5-fc8b5f430570,NaN,6598,8.849665,46.175962,2,3,Tenero,Tenero-Contra,5131.0,TI,21.0,TI,Tenero-Contra,97.0,93.0,97.0,93.0
2,f0c2bc0e-55ab-4eb1-98fa-edcb4a0ee01e,via albonago 43,6962,8.974113,46.013360,0,3,Viganello,Lugano,5192.0,TI,21.0,TI,Lugano,97.0,77.0,97.0,77.0
3,fbdcde66-0fd7-4304-a83e-70ecbb0f6ae7,Via San Gottardo 41,6500,9.032918,46.201556,0,1,Bellinzona,Bellinzona,5002.0,TI,21.0,TI,Bellinzona,97.0,93.0,97.0,93.0
4,2d7451a3-d7e1-4dc7-babf-ab237f2c02e4,Via F. Zorzi 17,6500,9.015443,46.187900,0,6,Bellinzona,Bellinzona,5002.0,TI,21.0,TI,Bellinzona,97.0,93.0,97.0,93.0

In [63]:
df_merged.isna().sum()

LocationId                      0
Street                       1524
ZIP                            57
longitude                       0
latitude                        0
#supermarkets                   0
#foodandbeverage                0
Ortschaftsname                 69
Gemeindename                   69
BfS-Id                         69
Kantonskürzel                  69
Kantons-Id                     78
Kanton                         78
Gemeinde                       78
Einkommenssteuer_Kanton        78
Einkommenssteuer_Gemeinde      78
Vermögenssteuer_Kanton         78
Vermögenssteuer_Gemeinde       78
dtype: int64

In [69]:
#nan_mask = df_merged.isna().any(axis=1)
nan_mask = df_merged['Gemeinde'].isna()
sub_df_with_nan = df_merged[nan_mask]

sub_df_with_nan

,LocationId,Street,ZIP,longitude,latitude,#supermarkets,#foodandbeverage,Ortschaftsname,Gemeindename,BfS-Id,Kantonskürzel,Kantons-Id,Kanton,Gemeinde,Einkommenssteuer_Kanton,Einkommenssteuer_Gemeinde,Vermögenssteuer_Kanton,Vermögenssteuer_Gemeinde
304,1aa64b21-463f-4bfe-852d-4b0f6de83a48,NaN,<NA>,8.227512,46.818188,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,7b799275-1fbd-42ee-8493-6760fe490ec4,NaN,<NA>,8.227512,46.818188,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,cd3a0605-7b0a-4d10-ba9a-265863a2c6da,NaN,<NA>,8.227512,46.818188,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
654,69648b43-3b2e-4ebf-b463-d99d6570ef9f,NaN,<NA>,8.227512,46.818188,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,dbb1bfca-563a-4c57-ba8f-e7daac41590f,NaN,<NA>,8.227512,46.818188,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13010,1bc6502b-2399-49fb-9c41-fc87d716e381,General-Dufourstrasse 104,2500,7.255409,47.143245,1,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13374,06a22f3c-6b4e-46ff-8321-9d71d6a01fa5,Neumarktstrasse 31,2500,7.251543,47.137128,6,39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13527,c2f47e1f-c83c-4647-86f2-c2fab95e2e38,Alexander-Schöni-Strasse 46,2500,7.251198,47.137731,7,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15872,944f1325-181d-4058-a369-3d8793695abe,NaN,<NA>,8.227512,46.818188,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17064,970d6e6d-8596-4263-b83c-35cd935b3991,NaN,<NA>,8.227512,46.818188,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN